name: Deploy on Ec2 Server
on:
  push:
    branches:
      - main

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy on pragati Server
      uses: appleboy/ssh-action@master
      with:
         host: '${{ secrets.SERVER }}'
         username: '${{ secrets.USERNAME }}'
         key: '${{ secrets.AWS_PRIVATE_KEY }}'
         port: '${{ secrets.PORT }}'
         script: |
          cd /var/www/html/test-project/
          git config --global --add safe.directory /var/www/html/test-project/
          sudo git stash
          sudo git pull origin main
